import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Activity, ArrowDownRight, ArrowUpRight, BarChart3, Bell, CalendarCheck2, ChevronLeft, ChevronRight, FileText, LayoutDashboard, Loader2, Menu, Search, ShieldCheck, Star, Store, Users, UserRoundCheck, X } from "lucide-react";
import * as admin from "../lib/admin2";
import type { AdminApplication, AdminBooking, AdminCustomer, AdminDocument, AdminReview } from "../lib/admin2";
import type { VerificationStatus } from "../types";

type Page = "dashboard" | "bookings" | "verification" | "providers" | "customers" | "marketplace" | "reports" | "reviews";
type Loaded = { bookings: AdminBooking[]; bookingsTotal: number; customers: AdminCustomer[]; customersTotal: number; providers: AdminApplication[]; providersApproved: number; providersPending: number; providersRejected: number; marketplaceTotal: number; reviews: AdminReview[]; reviewsTotal: number };
const emptyData: Loaded = { bookings: [], bookingsTotal: 0, customers: [], customersTotal: 0, providers: [], providersApproved: 0, providersPending: 0, providersRejected: 0, marketplaceTotal: 0, reviews: [], reviewsTotal: 0 };
const nav: Array<{ id: Page; label: string; icon: typeof LayoutDashboard }> = [
  { id: "dashboard", label: "Dashboard", icon: LayoutDashboard }, { id: "bookings", label: "Bookings", icon: CalendarCheck2 }, { id: "verification", label: "Verification", icon: ShieldCheck }, { id: "providers", label: "Providers", icon: UserRoundCheck }, { id: "customers", label: "Customers", icon: Users }, { id: "marketplace", label: "Marketplace", icon: Store }, { id: "reports", label: "Analytics", icon: BarChart3 }, { id: "reviews", label: "Reviews", icon: Star },
];
const fmtDate = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
const statusLabel = (value: string) => ({ pending: "Pending", confirmed: "Confirmed", accepted: "Accepted", in_progress: "In progress", completed: "Completed", cancelled: "Cancelled", rejected: "Rejected", approved: "Approved", suspended: "Suspended" } as Record<string, string>)[value] ?? value;
const paymentLabel = (value: string) => ({ unpaid: "Unpaid", pending: "Payment pending", paid: "Paid", refunded: "Refunded" } as Record<string, string>)[value] ?? value;
const statusClass = (value: string) => value === "completed" || value === "confirmed" || value === "accepted" || value === "approved" || value === "paid" || value === "active" ? "confirmed" : value === "cancelled" || value === "rejected" || value === "suspended" || value === "refunded" ? "cancelled" : "pending";
function Status({ value }: { value: string }) { return <span className={`m2-status ${statusClass(value)}`}>{statusLabel(value)}</span>; }
function PaymentStatus({ value }: { value: string }) { return <span className={`m2-status ${statusClass(value)}`}>{paymentLabel(value)}</span>; }
function Money({ price, currency }: { price: number | null; currency: string }) { return price == null ? <span>—</span> : <span>{price.toFixed(2)} {currency}</span>; }
function StatCard({ label, value, delta, icon, tone = "teal" }: { label: string; value: string; delta?: string; icon: ReactNode; tone?: string }) { const positive = !delta || delta.startsWith("+"); return <article className="m2-stat-card"><div className={`m2-stat-icon ${tone}`}>{icon}</div><p>{label}</p><strong>{value}</strong>{delta ? <span className={positive ? "positive" : "negative"}>{positive ? <ArrowUpRight size={13} /> : <ArrowDownRight size={13} />}{delta}</span> : null}</article>; }
function Empty({ text }: { text: string }) { return <div className="m2-placeholder"><span className="m2-placeholder-icon"><Activity size={22} /></span><h2>{text}</h2></div>; }

export default function AdminV2() {
  const [page, setPage] = useState<Page>("dashboard"); const [collapsed, setCollapsed] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); const [search, setSearch] = useState(""); const [notice, setNotice] = useState(""); const [data, setData] = useState<Loaded>(emptyData); const [loading, setLoading] = useState(true); const [busyId, setBusyId] = useState<string | null>(null); const [reviewBusyId, setReviewBusyId] = useState<string | null>(null); const [selected, setSelected] = useState<AdminApplication | null>(null); const [rejectReason, setRejectReason] = useState(""); const [providerStatus, setProviderStatus] = useState<VerificationStatus>("pending"); const [documents, setDocuments] = useState<AdminDocument[]>([]); const [documentsLoading, setDocumentsLoading] = useState(false);
  async function load() { setLoading(true); try { const [stats, bookings, customers, providers, marketplace, reviews] = await Promise.all([admin.fetchAdminStats(), admin.listBookings(), admin.listCustomers(), admin.listApplications(providerStatus), admin.listMarketplace(), admin.listAdminReviews()]); setData({ bookings: bookings.rows, bookingsTotal: stats.total_bookings, customers: customers.rows, customersTotal: stats.total_customers, providers, providersApproved: stats.approved_providers, providersPending: stats.providers_by_status.pending ?? 0, providersRejected: stats.providers_by_status.rejected ?? 0, marketplaceTotal: stats.published_listings, reviews: reviews.rows, reviewsTotal: reviews.total }); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to load admin data"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [providerStatus]);
  useEffect(() => {
    if (!selected) { setDocuments([]); return; }
    let active = true;
    setDocumentsLoading(true);
    void admin.listApplicationDocuments(selected.id).then((rows) => { if (active) setDocuments(rows); }).catch((error) => { if (active) setNotice(error instanceof Error ? error.message : "Unable to load documents"); }).finally(() => { if (active) setDocumentsLoading(false); });
    return () => { active = false; };
  }, [selected]);
  const q = search.trim().toLowerCase();
  const filteredBookings = useMemo(() => q ? data.bookings.filter(b => [b.id, b.customer_name, b.provider_name, b.service_category, b.status, b.payment_status, b.payment_method, b.location_text, b.currency].some(v => String(v ?? "").toLowerCase().includes(q))) : data.bookings, [data.bookings, q]);
  const filteredCustomers = useMemo(() => q ? data.customers.filter(c => [c.full_name, c.phone, c.city, c.account_status].some(v => String(v ?? "").toLowerCase().includes(q))) : data.customers, [data.customers, q]);
  const filteredProviders = useMemo(() => q ? data.providers.filter(p => [p.full_name, p.phone, p.city, p.profession, p.service_category, p.account_status].some(v => String(v ?? "").toLowerCase().includes(q))) : data.providers, [data.providers, q]);
  const filteredReviews = useMemo(() => q ? data.reviews.filter(r => [r.id, r.booking_id, r.customer_name, r.provider_name, r.comment, r.rating, r.is_hidden ? "hidden" : "visible"].some(v => String(v ?? "").toLowerCase().includes(q))) : data.reviews, [data.reviews, q]);
  const go = (next: Page) => { setPage(next); setMobileOpen(false); setSearch(""); window.scrollTo({ top: 0, behavior: "smooth" }); };
  async function providerAction(action: "approve" | "reject") { if (!selected) return; if (action === "reject" && !rejectReason.trim()) { setNotice("A rejection reason is required"); return; } setBusyId(selected.id); try { if (action === "approve") await admin.approveProvider(selected.id); else await admin.rejectProvider(selected.id, rejectReason); setSelected(null); setRejectReason(""); setNotice(action === "approve" ? "Provider approved" : "Provider rejected"); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Action failed"); } finally { setBusyId(null); } }
  async function toggleReview(reviewId: string) { setReviewBusyId(reviewId); try { await admin.toggleReviewVisibility(reviewId); setNotice("Review visibility updated"); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Review moderation failed"); } finally { setReviewBusyId(null); } }
  async function openDocument(document: AdminDocument) { try { const url = await admin.signedDocumentUrl(document.storage_path); window.open(url, "_blank", "noopener,noreferrer"); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to open document"); } }
  const currentLabel = nav.find(n => n.id === page)?.label ?? "Dashboard"; const pendingCount = data.providersPending;
  return <div className="m2-shell">
    <button className="m2-mobile-trigger" aria-label="Open admin navigation" onClick={() => setMobileOpen(true)}><Menu size={21} /></button>
    <aside className={`m2-sidebar ${collapsed ? "collapsed" : ""} ${mobileOpen ? "mobile-open" : ""}`}><div className="m2-sidebar-inner"><div className="m2-brand-row"><div className="m2-brand-mark">m<span /></div>{!collapsed && <div><b>maak<span>.</span></b><small>CONTROL CENTER</small></div>}<button className="m2-icon-btn mobile-only" aria-label="Close navigation" onClick={() => setMobileOpen(false)}><X size={18}/></button></div>{!collapsed && <button className="m2-search" onClick={() => document.getElementById("m2-global-search")?.focus()}><Search size={16}/><span>Search</span><kbd>⌘ K</kbd></button>}<nav className="m2-nav" aria-label="Admin navigation"><p>WORKSPACE</p>{nav.slice(0,1).map(item => { const Icon=item.icon; return <button key={item.id} className={page===item.id?"active":""} onClick={()=>go(item.id)} title={collapsed?item.label:undefined}><Icon size={18}/>{!collapsed&&<span>{item.label}</span>}</button>; })}<p>OPERATIONS</p>{nav.slice(1,6).map(item => { const Icon=item.icon; const badge=item.id==="verification"?pendingCount:item.id==="bookings"?data.bookingsTotal:0; return <button key={item.id} className={page===item.id?"active":""} onClick={()=>go(item.id)} title={collapsed?item.label:undefined}><Icon size={18}/>{!collapsed&&<span>{item.label}</span>}{!collapsed&&badge>0&&<b>{badge>99?"99+":badge}</b>}</button>; })}<p>INSIGHTS</p>{nav.slice(6).map(item => { const Icon=item.icon; return <button key={item.id} className={page===item.id?"active":""} onClick={()=>go(item.id)} title={collapsed?item.label:undefined}><Icon size={18}/>{!collapsed&&<span>{item.label}</span>}</button>; })}</nav><div className="m2-sidebar-bottom"><div className="m2-admin-user"><span className="m2-avatar">MK</span>{!collapsed&&<div><b>Maak Admin</b></div>}</div></div><button className="m2-collapse" onClick={()=>setCollapsed(v=>!v)} aria-label={collapsed?"Expand sidebar":"Collapse sidebar"}>{collapsed?<ChevronRight size={16}/>:<ChevronLeft size={16}/>}</button></div></aside>
    <main className="m2-main"><header className="m2-topbar"><div className="m2-breadcrumb"><span>Maak</span><ChevronRight size={14}/><strong>{currentLabel}</strong></div><div className="m2-top-actions"><label className="m2-global-search"><Search size={16}/><input id="m2-global-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search" aria-label="Search admin data"/></label><button className="m2-icon-btn" aria-label="Notifications" onClick={()=>setNotice("No new alerts")}><Bell size={18}/></button></div></header>
      {notice && <div className="m2-notice" role="status">{notice}</div>}
      {loading ? <section className="m2-placeholder"><span className="m2-placeholder-icon"><Activity size={22}/></span><h1>Loading…</h1></section> : page === "dashboard" ? <>
        <section className="m2-hero"><div><h1>Maak <em>Control Center.</em></h1><div className="m2-hero-actions"><button className="m2-btn primary" onClick={()=>go("verification")}><ShieldCheck size={16}/> Review queue · {pendingCount}</button><button className="m2-btn light" onClick={()=>go("bookings")}><CalendarCheck2 size={16}/> Bookings · {data.bookingsTotal}</button></div></div><div className="m2-hero-mini-grid"><div><span>BOOKINGS</span><b>{data.bookingsTotal}</b></div><div><span>CUSTOMERS</span><b>{data.customersTotal}</b></div><div><span>PROVIDERS</span><b>{data.providersApproved}</b></div><div><span>LISTINGS</span><b>{data.marketplaceTotal}</b></div></div></section>
        <section className="m2-grid m2-grid-4" aria-label="Key metrics"><StatCard label="Customers" value={data.customersTotal.toLocaleString("fr-MA")} icon={<Users size={18}/>} /><StatCard label="Bookings" value={data.bookingsTotal.toLocaleString("fr-MA")} icon={<CalendarCheck2 size={18}/>} tone="blue"/><StatCard label="Published listings" value={data.marketplaceTotal.toLocaleString("fr-MA")} icon={<Store size={18}/>} tone="gold"/><StatCard label="Pending verification" value={data.providersPending.toLocaleString("fr-MA")} icon={<ShieldCheck size={18}/>} tone="clay"/></section>
        <section className="m2-grid m2-grid-main"><article className="m2-card"><div className="m2-card-head"><div><span className="m2-kicker muted">VERIFICATION</span><h2>Provider pipeline</h2></div><button className="m2-link" onClick={()=>go("verification")}>Open queue <ChevronRight size={14}/></button></div><div className="m2-pulse"><div><span>Pending</span><b>{data.providersPending}</b><i><em style={{width:`${Math.min(100,data.providersPending?100:0)}%`}}/></i></div><div><span>Approved</span><b>{data.providersApproved}</b><i><em style={{width:`${data.providersApproved+data.providersPending+data.providersRejected?(data.providersApproved/(data.providersApproved+data.providersPending+data.providersRejected))*100:0}%`}}/></i></div><div><span>Rejected</span><b>{data.providersRejected}</b><i><em style={{width:`${data.providersApproved+data.providersPending+data.providersRejected?(data.providersRejected/(data.providersApproved+data.providersPending+data.providersRejected))*100:0}%`}}/></i></div></div></article><article className="m2-card m2-attention"><div className="m2-card-head"><div><span className="m2-kicker clay">RECENT OPERATIONS</span><h2>Latest bookings</h2></div><button className="m2-link" onClick={()=>go("bookings")}>View all <ChevronRight size={14}/></button></div>{data.bookings.slice(0,4).map(b=><button key={b.id} className="m2-action-row" onClick={()=>go("bookings")}><span className="m2-action-icon"><CalendarCheck2 size={16}/></span><span><b>{b.service_category||"Service"}</b><small>{b.customer_name||"Customer"} · {b.location_text??""} · <Money price={b.price} currency={b.currency}/></small></span><Status value={b.status}/></button>)}{data.bookings.length===0&&<Empty text="No bookings in the current database."/>}</article></section>
        <section className="m2-grid m2-grid-main"><article className="m2-card"><div className="m2-card-head"><div><span className="m2-kicker muted">PLATFORM DATA</span><h2>Latest booking activity</h2></div></div><div className="m2-table-wrap"><table><thead><tr><th>Booking</th><th>Customer</th><th>Provider</th><th>Service</th><th>Status</th><th>Payment</th><th>Amount</th><th>Created</th></tr></thead><tbody>{filteredBookings.slice(0,8).map(b=><tr key={b.id}><td><b>{b.id.slice(0,8)}</b></td><td>{b.customer_name||"—"}</td><td>{b.provider_name||"—"}</td><td>{b.service_category||"—"}</td><td><Status value={b.status}/></td><td><PaymentStatus value={b.payment_status}/></td><td><Money price={b.price} currency={b.currency}/></td><td>{fmtDate(b.created_at)}</td></tr>)}</tbody></table>{filteredBookings.length===0&&<Empty text="No matching bookings."/>}</div></article><article className="m2-card m2-side-card"><div className="m2-card-head"><div><span className="m2-kicker muted">PLATFORM PULSE</span><h2>Live state</h2></div><Activity size={17}/></div><div className="m2-pulse"><div><span>Published listings</span><b>{data.marketplaceTotal}</b></div><div><span>Customers</span><b>{data.customersTotal}</b></div><div><span>Approved providers</span><b>{data.providersApproved}</b></div><div><span>Review queue</span><b>{data.providersPending}</b></div></div></article></section>
      </> : page === "verification" ? <section className="m2-card m2-page-card"><div className="m2-card-head"><div><span className="m2-kicker muted">PROVIDER VERIFICATION</span><h2>Applications</h2></div><select className="m2-filter" value={providerStatus} onChange={e=>setProviderStatus(e.target.value as VerificationStatus)}><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></div><div className="m2-table-wrap"><table><thead><tr><th>Name</th><th>Profession</th><th>City</th><th>Experience</th><th>Status</th><th>Updated</th><th></th></tr></thead><tbody>{filteredProviders.map(p=><tr key={p.id}><td><b>{p.full_name||"—"}</b><small>{p.phone||""}</small></td><td>{p.profession||"—"}</td><td>{p.city||"—"}</td><td>{p.experience_years??0} yrs</td><td><Status value={p.verification_status}/></td><td>{fmtDate(p.updated_at)}</td><td><button className="m2-link" onClick={()=>{setSelected(p);setRejectReason("")}}>Review</button></td></tr>)}</tbody></table>{filteredProviders.length===0&&<Empty text="No applications match this queue."/>}</div></section>
      : page === "bookings" ? <section className="m2-card m2-page-card"><div className="m2-card-head"><div><span className="m2-kicker muted">BOOKINGS</span><h2>All bookings</h2></div><span className="count-badge">{data.bookingsTotal}</span></div><div className="m2-table-wrap"><table><thead><tr><th>Booking</th><th>Customer</th><th>Provider</th><th>Service</th><th>Status</th><th>Payment</th><th>Amount</th><th>Method</th><th>Date</th><th>Location</th></tr></thead><tbody>{filteredBookings.map(b=><tr key={b.id}><td><b>{b.id.slice(0,8)}</b></td><td>{b.customer_name||"—"}</td><td>{b.provider_name||"—"}</td><td>{b.service_category||"—"}</td><td><Status value={b.status}/></td><td><PaymentStatus value={b.payment_status}/></td><td><Money price={b.price} currency={b.currency}/></td><td>{b.payment_method||"—"}</td><td>{fmtDate(b.service_date)}</td><td>{b.location_text||"—"}</td></tr>)}</tbody></table>{filteredBookings.length===0&&<Empty text="No bookings found."/>}</div></section>
      : page === "customers" ? <section className="m2-card m2-page-card"><div className="m2-card-head"><div><span className="m2-kicker muted">CUSTOMERS</span><h2>Customer accounts</h2></div><span className="count-badge">{data.customersTotal}</span></div><div className="m2-table-wrap"><table><thead><tr><th>Name</th><th>Phone</th><th>City</th><th>Status</th><th>Created</th></tr></thead><tbody>{filteredCustomers.map(c=><tr key={c.id}><td><b>{c.full_name||"Unnamed user"}</b></td><td>{c.phone||"—"}</td><td>{c.city||"—"}</td><td><Status value={c.account_status}/></td><td>{fmtDate(c.created_at)}</td></tr>)}</tbody></table>{filteredCustomers.length===0&&<Empty text="No customer accounts found."/>}</div></section>
      : page === "providers" ? <section className="m2-card m2-page-card"><div className="m2-card-head"><div><span className="m2-kicker muted">PROVIDERS</span><h2>Provider accounts</h2></div><button className="m2-link" onClick={()=>go("verification")}>Verification queue <ChevronRight size={14}/></button></div><div className="m2-table-wrap"><table><thead><tr><th>Name</th><th>Profession</th><th>City</th><th>Experience</th><th>Verification</th><th>Account</th></tr></thead><tbody>{filteredProviders.map(p=><tr key={p.id}><td>{p.full_name||"—"}</td><td>{p.profession||"—"}</td><td>{p.city||"—"}</td><td>{p.experience_years??0}</td><td><Status value={p.verification_status}/></td><td><Status value={p.account_status}/></td></tr>)}</tbody></table>{filteredProviders.length===0&&<Empty text="No provider records in this queue."/>}</div></section>
      : page === "reviews" ? <section className="m2-card m2-page-card"><div className="m2-card-head"><div><span className="m2-kicker muted">REVIEWS</span><h2>Review moderation</h2></div><span className="count-badge">{data.reviewsTotal}</span></div><div className="m2-table-wrap"><table><thead><tr><th>Customer</th><th>Provider</th><th>Rating</th><th>Comment</th><th>Visibility</th><th>Created</th><th>Action</th></tr></thead><tbody>{filteredReviews.map(review=><tr key={review.id}><td>{review.customer_name||"—"}</td><td>{review.provider_name||"—"}</td><td><span style={{display:"inline-flex",alignItems:"center",gap:4}}><Star size={14} fill="currentColor"/> {review.rating}/5</span></td><td style={{maxWidth:320}}>{review.comment||"—"}</td><td><Status value={review.is_hidden?"suspended":"approved"}/></td><td>{fmtDate(review.created_at)}</td><td><button className="m2-btn light" disabled={reviewBusyId===review.id} onClick={()=>void toggleReview(review.id)}>{reviewBusyId===review.id?"Working…":review.is_hidden?"Show":"Hide"}</button></td></tr>)}</tbody></table>{filteredReviews.length===0&&<Empty text="No reviews found."/>}</div></section>
      : <section className="m2-placeholder"><span className="m2-placeholder-icon"><BarChart3 size={22}/></span><span className="m2-kicker">{currentLabel.toUpperCase()}</span><h1>{currentLabel}</h1><button className="m2-btn primary" onClick={()=>go("dashboard")}>Back to dashboard</button></section>}
      {selected && <div className="m2-modal-backdrop" role="presentation"><section className="m2-modal" role="dialog" aria-modal="true" aria-label="Provider review"><div className="m2-card-head"><div><span className="m2-kicker clay">REVIEW APPLICATION</span><h2>{selected.full_name||"Applicant"}</h2></div><button className="m2-icon-btn" aria-label="Close review" onClick={()=>setSelected(null)}><X size={18}/></button></div><div className="m2-review-grid"><div><small>Profession</small><b>{selected.profession||"—"}</b></div><div><small>City</small><b>{selected.city||"—"}</b></div><div><small>Experience</small><b>{selected.experience_years??0} years</b></div><div><small>Service</small><b>{selected.service_category||"—"}</b></div></div><div className="m2-review-docs"><div className="m2-card-head"><div><span className="m2-kicker muted">VERIFICATION DOCUMENTS</span><h3>Uploaded documents</h3></div></div>{documentsLoading ? <span className="m2-status pending"><Loader2 size={13}/> Loading…</span> : documents.length ? <div>{documents.map(doc=><div key={doc.id} className="m2-action-row"><span className="m2-action-icon"><FileText size={16}/></span><span><b>{doc.document_type}</b><small>{doc.status} · {fmtDate(doc.created_at)}</small></span><button className="m2-link" type="button" onClick={()=>void openDocument(doc)}>Open</button></div>)}</div> : <small>No documents uploaded.</small>}</div><label className="field-label" htmlFor="m2-rejection-reason">Rejection reason</label><textarea id="m2-rejection-reason" className="field" value={rejectReason} onChange={e=>setRejectReason(e.target.value)} aria-label="Rejection reason"/><div className="m2-modal-actions"><button className="m2-btn light" onClick={()=>setSelected(null)}>Cancel</button><button className="m2-btn danger" disabled={!!busyId} onClick={()=>void providerAction("reject")}>Reject</button><button className="m2-btn primary" disabled={!!busyId} onClick={()=>void providerAction("approve")}>{busyId?"Working…":"Approve"}</button></div></section></div>}
    </main>
  </div>;
}
