import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Activity, Ban, BookOpen, CalendarDays, Check, ChevronDown, ChevronLeft, Clock3, ExternalLink, FileText, LayoutDashboard, Loader2, LogOut, RefreshCw, Search, Settings, ShieldCheck, UserRoundCheck, Users, X } from "lucide-react";
import { Logo } from "../components/atoms";
import { useAuth } from "../auth";
import { useToast } from "../context";
import * as admin from "../lib/admin";
import type { AdminApplication, AdminBooking, AdminCustomer, AdminDocument } from "../lib/admin";
import { BOOKING_STATUS_LABELS } from "../lib/bookings";
import type { BookingStatus, VerificationStatus } from "../types";
import { useLanguage } from "../i18n";
import "../styles/admin-command-center.css";

type Section = "overview" | "providers" | "customers" | "bookings" | "system";
type Copy = Record<string, string>;
const AR: Copy = { dashboard:"نظرة عامة",providers:"مقدمو الخدمات",customers:"العملاء",bookings:"الحجوزات",system:"الإعدادات",control:"مركز التحكم",subtitle:"إدارة منصة Maak",refresh:"تحديث",verification:"طلبات التحقق",pending:"قيد المراجعة",approved:"معتمد",rejected:"مرفوض",totalUsers:"العملاء",totalBookings:"الحجوزات",recent:"آخر الحجوزات",noData:"لا توجد بيانات",search:"بحث",review:"عرض",suspend:"تعليق",reactivate:"تفعيل",cancel:"إلغاء الحجز",close:"إغلاق",details:"عرض الكل",active:"نشط",suspended:"معلّق",role:"الدور",city:"المدينة",phone:"الهاتف",created:"تاريخ الإنشاء",service:"الخدمة",status:"الحالة",date:"التاريخ",customer:"العميل",provider:"مقدم الخدمة",account:"الحساب",systemTitle:"الإعدادات",documents:"الوثائق",accept:"اعتماد",reject:"رفض",rejectReason:"سبب الرفض",confirm:"تأكيد",back:"العودة إلى التطبيق",admin:"المسؤول",signout:"تسجيل الخروج",profile:"حساب المسؤول",language:"اللغة",accountInfo:"معلومات الحساب",open:"فتح",providerReview:"ملف مقدم الخدمة",customerDetails:"تفاصيل العميل",bookingDetails:"تفاصيل الحجز",all:"الكل",roleAdmin:"مسؤول",roleProvider:"مقدم خدمة",roleCustomer:"عميل",emptyProviders:"لا توجد طلبات في هذه الفئة",emptyCustomers:"لا يوجد عملاء",emptyBookings:"لا توجد حجوزات",cancelConfirm:"هل تريد إلغاء هذا الحجز؟",accountConfirm:"هل تريد تغيير حالة هذا الحساب؟",menu:"القائمة",activity:"النشاط",overview:"نظرة عامة",serviceArea:"نطاق الخدمة",experience:"الخبرة",coverage:"نطاق التغطية",applied:"تاريخ الطلب",profileDetails:"بيانات الملف",important:"تحتاج إلى مراجعة",noPending:"لا توجد طلبات تحقق حالياً",noBookings:"لا توجد حجوزات حتى الآن",noCustomers:"لا توجد حسابات عملاء",marketplace:"السوق",accountStatus:"حالة الحساب",loading:"جارٍ التحميل…",systemInfo:"الحساب والصلاحيات" };
const FR: Copy = { dashboard:"Vue d’ensemble",providers:"Prestataires",customers:"Clients",bookings:"Réservations",system:"Paramètres",control:"Centre de contrôle",subtitle:"Gestion de la plateforme Maak",refresh:"Actualiser",verification:"Vérifications",pending:"En attente",approved:"Approuvé",rejected:"Refusé",totalUsers:"Clients",totalBookings:"Réservations",recent:"Dernières réservations",noData:"Aucune donnée",search:"Rechercher",review:"Voir",suspend:"Suspendre",reactivate:"Activer",cancel:"Annuler",close:"Fermer",details:"Tout voir",active:"Actif",suspended:"Suspendu",role:"Rôle",city:"Ville",phone:"Téléphone",created:"Créé le",service:"Service",status:"Statut",date:"Date",customer:"Client",provider:"Prestataire",account:"Compte",systemTitle:"Paramètres",documents:"Documents",accept:"Approuver",reject:"Refuser",rejectReason:"Motif",confirm:"Confirmer",back:"Retour",admin:"Administrateur",signout:"Déconnexion",profile:"Compte administrateur",language:"Langue",accountInfo:"Compte",open:"Ouvrir",providerReview:"Fiche prestataire",customerDetails:"Fiche client",bookingDetails:"Détails réservation",all:"Tous",roleAdmin:"Administrateur",roleProvider:"Prestataire",roleCustomer:"Client",emptyProviders:"Aucune demande dans cette catégorie",emptyCustomers:"Aucun client",emptyBookings:"Aucune réservation",cancelConfirm:"Annuler cette réservation ?",accountConfirm:"Modifier le statut de ce compte ?",menu:"Menu",activity:"Activité",overview:"Vue d’ensemble",serviceArea:"Zone de service",experience:"Expérience",coverage:"Zone couverte",applied:"Date de demande",profileDetails:"Profil",important:"À traiter",noPending:"Aucune demande de vérification",noBookings:"Aucune réservation pour le moment",noCustomers:"Aucun compte client",marketplace:"Marché",accountStatus:"Statut du compte",loading:"Chargement…",systemInfo:"Compte et accès" };
function StatusBadge({ status, label }: { status: string; label?: string }) { const s=status.toLowerCase(); const ok=["approved","active","completed","accepted"].includes(s); const no=["rejected","suspended","cancelled"].includes(s); return <span className={`ap-badge ${ok?"ok":no?"no":"warn"}`}><i />{label??status}</span>; }
function initials(name:string|null){return(name||"M").trim().split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase();}

export default function Admin({ switchRole }:{ switchRole:()=>void }){
 const {lang,toggleLang,t}=useLanguage(); const {profile}=useAuth(); const {showToast}=useToast(); const copy=lang==="fr"?FR:AR;
 const [section,setSection]=useState<Section>("overview"); const [counts,setCounts]=useState({pending:0,approved:0,rejected:0}); const [customers,setCustomers]=useState<{rows:AdminCustomer[];total:number}>({rows:[],total:0}); const [bookings,setBookings]=useState<{rows:AdminBooking[];total:number}>({rows:[],total:0}); const [providerStatus,setProviderStatus]=useState<VerificationStatus>("pending"); const [providers,setProviders]=useState<AdminApplication[]>([]); const [search,setSearch]=useState(""); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [selectedProvider,setSelectedProvider]=useState<AdminApplication|null>(null); const [selectedCustomer,setSelectedCustomer]=useState<AdminCustomer|null>(null); const [selectedBooking,setSelectedBooking]=useState<AdminBooking|null>(null); const [documents,setDocuments]=useState<AdminDocument[]>([]); const [docsLoading,setDocsLoading]=useState(false); const [rejectReason,setRejectReason]=useState(""); const [busyId,setBusyId]=useState<string|null>(null);
 const loadCore=async()=>{setRefreshing(true);try{const[pending,approved,rejected,users,bks,apps]=await Promise.all([admin.countByStatus("pending"),admin.countByStatus("approved"),admin.countByStatus("rejected"),admin.listCustomers(),admin.listBookings(),admin.listApplications(providerStatus)]);setCounts({pending,approved,rejected});setCustomers(users);setBookings(bks);setProviders(apps);}catch(e){showToast(e instanceof Error?e.message:t("common.error"));}finally{setRefreshing(false);setLoading(false);}};
 useEffect(()=>{void loadCore();},[providerStatus]);
 const filteredUsers=useMemo(()=>{const q=search.trim().toLowerCase();return q?customers.rows.filter(u=>[u.full_name,u.phone,u.city,u.role,u.account_status].some(v=>String(v??"").toLowerCase().includes(q))):customers.rows;},[customers.rows,search]);
 const filteredProviders=useMemo(()=>{const q=search.trim().toLowerCase();return q?providers.filter(p=>[p.full_name,p.phone,p.city,p.profession,p.service_category,p.account_status].some(v=>String(v??"").toLowerCase().includes(q))):providers;},[providers,search]);
 const filteredBookings=useMemo(()=>{const q=search.trim().toLowerCase();return q?bookings.rows.filter(b=>[b.customer_name,b.provider_name,b.service_category,b.status,b.location_text].some(v=>String(v??"").toLowerCase().includes(q))):bookings.rows;},[bookings.rows,search]);
 const fmt=(iso:string|null)=>iso?new Intl.DateTimeFormat(lang==="fr"?"fr-FR":"ar-MA",{dateStyle:"medium",timeStyle:"short"}).format(new Date(iso)):"—";
 const roleLabel=(r:string)=>r==="admin"?copy.roleAdmin:r==="provider"?copy.roleProvider:copy.roleCustomer;
 const bookingLabel=(s:string)=>{const key=BOOKING_STATUS_LABELS[s as BookingStatus];return key?t(key):s;};
 const navigate=(next:Section)=>{setSection(next);setSearch("");};
 async function openProvider(p:AdminApplication){setSelectedProvider(p);setRejectReason("");setDocuments([]);setDocsLoading(true);try{setDocuments(await admin.listApplicationDocuments(p.id));}catch(e){showToast(e instanceof Error?e.message:t("common.error"));}finally{setDocsLoading(false);}}
 async function providerAction(action:"approve"|"reject"){if(!selectedProvider)return;if(action==="reject"&&!rejectReason.trim()){showToast(t("adm.errReasonRequired"));return;}setBusyId(selectedProvider.id);try{if(action==="approve")await admin.approveProvider(selectedProvider.id);else await admin.rejectProvider(selectedProvider.id,rejectReason);showToast(action==="approve"?copy.accept:copy.reject);setSelectedProvider(null);await loadCore();}catch(e){showToast(e instanceof Error?e.message:t("common.error"));}finally{setBusyId(null);}}
 async function accountAction(u:AdminCustomer|AdminApplication){if(u.id===profile?.id)return;const next=u.account_status==="suspended"?"active":"suspended";setBusyId(u.id);try{await admin.setAccountStatus(u.id,next);showToast(next==="active"?copy.reactivate:copy.suspend);setSelectedCustomer(null);setSelectedProvider(null);await loadCore();}catch(e){showToast(e instanceof Error?e.message:t("common.error"));}finally{setBusyId(null);}}
 async function cancelBooking(){if(!selectedBooking)return;setBusyId(selectedBooking.id);try{await admin.cancelBooking(selectedBooking.id,lang==="fr"?"Annulation administrative":"إلغاء إداري");showToast(copy.cancel);setSelectedBooking(null);await loadCore();}catch(e){showToast(e instanceof Error?e.message:t("common.error"));}finally{setBusyId(null);}}
 async function openDocument(path:string){try{window.open(await admin.signedDocumentUrl(path),"_blank","noopener,noreferrer");}catch(e){showToast(e instanceof Error?e.message:t("common.error"));}}
 function navButton(key:Section,icon:ReactNode,label:string,count?:number){return <button className={section===key?"active":""} onClick={()=>navigate(key)}>{icon}<span>{label}</span>{count&&count>0?<b className="nav-count">{count>99?"99+":count}</b>:null}</button>;}
 if(loading)return <div className="admin-pro admin-loading"><Logo size="sm"/><Loader2 className="spin" size={26}/></div>;
 const verificationCount=(s:VerificationStatus)=>s==="pending"?counts.pending:s==="approved"?counts.approved:counts.rejected;
 return <div className="admin-pro" dir={lang==="fr"?"ltr":"rtl"}>
  <aside className="admin-pro-side"><div className="admin-pro-brand"><Logo variant="lockup" size="sm"/><div><strong>Maak</strong><small>{copy.control}</small></div></div><nav className="admin-pro-nav">{navButton("overview",<LayoutDashboard/>,copy.dashboard)}{navButton("providers",<UserRoundCheck/>,copy.providers,counts.pending)}{navButton("customers",<Users/>,copy.customers,customers.total)}{navButton("bookings",<BookOpen/>,copy.bookings,bookings.total)}{navButton("system",<Settings/>,copy.system)}</nav><div className="admin-pro-side-footer"><button onClick={toggleLang}><Activity/><span>{lang==="fr"?"العربية":"Français"}</span></button><button onClick={switchRole}><LogOut/><span>{copy.signout}</span></button></div></aside>
  <main className="admin-pro-main"><header className="admin-pro-top"><div className="admin-pro-title"><span className="ap-eyebrow">Maak · {copy.control}</span><h1>{section==="overview"?copy.dashboard:section==="providers"?copy.providers:section==="customers"?copy.customers:section==="bookings"?copy.bookings:copy.system}</h1><p>{copy.subtitle}</p></div><div className="admin-pro-actions"><button className="ap-icon" onClick={()=>void loadCore()} disabled={refreshing} aria-label={copy.refresh}><RefreshCw className={refreshing?"spin":""}/></button><button className="ap-primary" onClick={()=>{navigate("providers");setProviderStatus("pending");}}><ShieldCheck/>{copy.verification}<span>{counts.pending}</span></button></div></header>
   <section className="admin-pro-kpis"><button className="ap-kpi accent" onClick={()=>{navigate("providers");setProviderStatus("pending");}}><div className="ap-kpi-top"><span>{copy.pending}</span><Clock3/></div><strong>{counts.pending}</strong><small>{copy.verification}</small></button><button className="ap-kpi" onClick={()=>{navigate("providers");setProviderStatus("approved");}}><div className="ap-kpi-top"><span>{copy.approved}</span><Check/></div><strong>{counts.approved}</strong><small>{copy.providers}</small></button><button className="ap-kpi" onClick={()=>navigate("customers")}><div className="ap-kpi-top"><span>{copy.totalUsers}</span><Users/></div><strong>{customers.total}</strong><small>{copy.account}</small></button><button className="ap-kpi" onClick={()=>navigate("bookings")}><div className="ap-kpi-top"><span>{copy.totalBookings}</span><CalendarDays/></div><strong>{bookings.total}</strong><small>{copy.bookings}</small></button></section>
   {section==="overview"&&<div className="admin-pro-grid"><section className="ap-panel ap-panel-featured"><div className="ap-panel-head"><div><span className="ap-section-label">{copy.verification}</span><h2>{copy.important}</h2></div><button className="ap-btn" onClick={()=>{navigate("providers");setProviderStatus("pending");}}>{copy.details}<ChevronLeft/></button></div><div className="ap-panel-body">{providers.length===0?<div className="ap-empty"><ShieldCheck size={30}/><strong>{copy.noPending}</strong></div>:<div className="ap-list">{providers.slice(0,5).map(p=><div className="ap-row" key={p.id}><div className="ap-avatar">{p.avatar_url?<img src={p.avatar_url} alt=""/>:<span>{initials(p.full_name)}</span>}</div><div className="ap-row-main"><strong>{p.full_name||"—"}<StatusBadge status={p.verification_status} label={copy.pending}/></strong><span>{p.profession||p.service_category||"—"}{p.city?` · ${p.city}`:""}</span></div><div className="ap-actions"><button className="ap-btn" onClick={()=>void openProvider(p)}>{copy.review}<ChevronLeft size={14}/></button></div></div>)}</div>}</div></section>
   <section className="ap-panel"><div className="ap-panel-head"><div><span className="ap-section-label">{copy.recent}</span><h2>{copy.bookings}</h2></div><button className="ap-btn" onClick={()=>navigate("bookings")}>{copy.details}<ChevronLeft/></button></div><div className="ap-panel-body">{bookings.rows.slice(0,5).length===0?<div className="ap-empty"><CalendarDays size={30}/><strong>{copy.noBookings}</strong></div>:<div className="ap-list">{bookings.rows.slice(0,5).map(b=><button className="ap-row ap-row-button" key={b.id} onClick={()=>setSelectedBooking(b)}><div className="ap-activity-icon"><BookOpen size={16}/></div><div className="ap-row-main"><strong>{b.service_category||"—"}</strong><span>{b.customer_name||"—"} · {fmt(b.created_at)}</span></div><StatusBadge status={b.status} label={bookingLabel(b.status)}/></button>)}</div>}</div></section></div>}
   {section==="providers"&&<section className="ap-panel"><div className="ap-panel-head"><div><span className="ap-section-label">{copy.marketplace}</span><h2>{copy.providers}</h2></div><button className="ap-icon" onClick={()=>void loadCore()} aria-label={copy.refresh}><RefreshCw className={refreshing?"spin":""}/></button></div><div className="ap-toolbar"><div className="ap-search-wrap"><Search size={16}/><input className="ap-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder={copy.search}/></div><div className="ap-filters">{(["pending","approved","rejected"] as VerificationStatus[]).map(s=><button key={s} className={`ap-filter ${providerStatus===s?"active":""}`} onClick={()=>setProviderStatus(s)}>{s==="pending"?copy.pending:s==="approved"?copy.approved:copy.rejected}<b>{verificationCount(s)}</b></button>)}</div></div><div className="ap-panel-body"><div className="ap-list">{filteredProviders.length===0?<div className="ap-empty"><UserRoundCheck size={30}/><strong>{copy.emptyProviders}</strong></div>:filteredProviders.map(p=><div className="ap-row" key={p.id}><div className="ap-avatar">{p.avatar_url?<img src={p.avatar_url} alt=""/>:<span>{initials(p.full_name)}</span>}</div><div className="ap-row-main"><strong>{p.full_name||"—"}<StatusBadge status={p.verification_status}/></strong><span>{p.profession||p.service_category||"—"}{p.city?` · ${p.city}`:""}{p.experience_years!=null?` · ${p.experience_years} ${copy.experience.toLowerCase()}`:""}</span></div><div className="ap-actions"><button className="ap-btn" onClick={()=>void openProvider(p)}>{copy.review}<ChevronLeft size={14}/></button>{p.account_status==="suspended"?<button className="ap-btn success" disabled={busyId===p.id} onClick={()=>void accountAction(p)}>{copy.reactivate}</button>:<button className="ap-btn" disabled={busyId===p.id||p.id===profile?.id} onClick={()=>void accountAction(p)}>{copy.suspend}</button>}</div></div>)}</div></div></section>}
   {section==="customers"&&<section className="ap-panel"><div className="ap-panel-head"><div><span className="ap-section-label">{copy.account}</span><h2>{copy.customers}</h2></div></div><div className="ap-toolbar"><div className="ap-search-wrap"><Search size={16}/><input className="ap-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder={copy.search}/></div></div><div className="ap-panel-body"><div className="ap-list">{filteredUsers.length===0?<div className="ap-empty"><Users size={30}/><strong>{copy.noCustomers}</strong></div>:filteredUsers.map(u=><div className="ap-row" key={u.id}><div className="ap-avatar"><span>{initials(u.full_name)}</span></div><div className="ap-row-main"><strong>{u.full_name||"—"}<StatusBadge status={u.account_status} label={u.account_status==="active"?copy.active:copy.suspended}/></strong><span>{u.city||"—"} · {u.phone||"—"} · {fmt(u.created_at)}</span></div><div className="ap-actions"><button className="ap-btn" onClick={()=>setSelectedCustomer(u)}>{copy.review}</button></div></div>)}</div></div></section>}
   {section==="bookings"&&<section className="ap-panel"><div className="ap-panel-head"><div><span className="ap-section-label">{copy.marketplace}</span><h2>{copy.bookings}</h2></div></div><div className="ap-toolbar"><div className="ap-search-wrap"><Search size={16}/><input className="ap-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder={copy.search}/></div></div><div className="ap-table-wrap"><table className="ap-table"><thead><tr><th>{copy.service}</th><th>{copy.customer}</th><th>{copy.provider}</th><th>{copy.status}</th><th>{copy.date}</th><th/></tr></thead><tbody>{filteredBookings.length===0?<tr><td colSpan={6}><div className="ap-empty">{copy.emptyBookings}</div></td></tr>:filteredBookings.map(b=><tr key={b.id}><td><strong>{b.service_category||"—"}</strong><small>{b.location_text||""}</small></td><td>{b.customer_name||"—"}</td><td>{b.provider_name||"—"}</td><td><StatusBadge status={b.status} label={bookingLabel(b.status)}/></td><td>{fmt(b.created_at)}</td><td><button className="ap-btn" onClick={()=>setSelectedBooking(b)}>{copy.review}</button></td></tr>)}</tbody></table></div></section>}
   {section==="system"&&<section className="ap-panel"><div className="ap-panel-head"><div><span className="ap-section-label">{copy.account}</span><h2>{copy.systemInfo}</h2></div></div><div className="ap-panel-body ap-settings-grid"><div className="ap-info"><h3>{copy.profile}</h3><div className="ap-info-grid"><div><span>{copy.role}</span><strong>{copy.admin}</strong></div><div><span>{copy.language}</span><strong>{lang==="fr"?"Français":"العربية"}</strong></div><div><span>{copy.status}</span><strong>{copy.active}</strong></div><div><span>{copy.account}</span><strong>{profile?.full_name||"—"}</strong></div></div></div><div className="ap-info"><h3>{copy.language}</h3><button className="ap-btn" onClick={toggleLang}><Activity size={15}/>{lang==="fr"?"العربية":"Français"}<ChevronDown size={14}/></button></div></div></section>}
  </main>
  <nav className="ap-mobile-nav">{navButton("overview",<LayoutDashboard/>,copy.dashboard)}{navButton("providers",<UserRoundCheck/>,copy.providers,counts.pending)}{navButton("customers",<Users/>,copy.customers)}{navButton("bookings",<BookOpen/>,copy.bookings)}{navButton("system",<Settings/>,copy.system)}</nav>
  {selectedProvider&&<div className="ap-drawer-overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setSelectedProvider(null);}}><aside className="ap-drawer" role="dialog" aria-modal="true" aria-label={copy.providerReview}><div className="ap-drawer-head"><div><span className="ap-section-label">{copy.providerReview}</span><h2>{selectedProvider.full_name||"—"}</h2><p>{selectedProvider.profession||selectedProvider.service_category||"—"}</p></div><button className="ap-icon" onClick={()=>setSelectedProvider(null)} aria-label={copy.close}><X/></button></div><div className="ap-drawer-body"><div className="ap-info"><h3>{copy.profileDetails}</h3><div className="ap-info-grid"><div><span>{copy.city}</span><strong>{selectedProvider.city||"—"}</strong></div><div><span>{copy.phone}</span><strong>{selectedProvider.phone||"—"}</strong></div><div><span>{copy.experience}</span><strong>{selectedProvider.experience_years??"—"}</strong></div><div><span>{copy.status}</span><strong><StatusBadge status={selectedProvider.verification_status}/></strong></div></div></div><div className="ap-info"><h3>{copy.service}</h3><p>{selectedProvider.service_category||selectedProvider.profession||"—"}</p><p className="ap-muted-text">{selectedProvider.bio||"—"}</p></div><div className="ap-info"><h3>{copy.documents}</h3>{docsLoading?<div className="ap-empty"><Loader2 className="spin" size={22}/></div>:documents.length===0?<div className="ap-empty"><FileText size={24}/><strong>{copy.noData}</strong></div>:<div className="ap-docs">{documents.map(d=><button key={d.id} onClick={()=>void openDocument(d.storage_path)}><FileText size={17}/><span>{d.document_type}</span><small>{d.status}</small><ExternalLink size={14}/></button>)}</div>}</div>{selectedProvider.rejection_reason?<div className="ap-info"><h3>{copy.rejectReason}</h3><p>{selectedProvider.rejection_reason}</p></div>:null}{providerStatus==="pending"?<div className="ap-confirm"><p>{copy.confirm}</p><textarea value={rejectReason} onChange={e=>setRejectReason(e.target.value)} placeholder={copy.rejectReason} aria-label={copy.rejectReason}/></div>:null}</div><div className="ap-drawer-foot">{providerStatus==="pending"?<><button className="ap-btn danger" disabled={busyId===selectedProvider.id} onClick={()=>void providerAction("reject")}><Ban size={15}/>{copy.reject}</button><button className="ap-primary" disabled={busyId===selectedProvider.id} onClick={()=>void providerAction("approve")}><Check size={15}/>{copy.accept}</button></>:null}{selectedProvider.account_status==="suspended"?<button className="ap-btn success" disabled={busyId===selectedProvider.id} onClick={()=>void accountAction(selectedProvider)}>{copy.reactivate}</button>:<button className="ap-btn" disabled={busyId===selectedProvider.id||selectedProvider.id===profile?.id} onClick={()=>void accountAction(selectedProvider)}>{copy.suspend}</button>}</div></aside></div>}
  {selectedCustomer&&<div className="ap-drawer-overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setSelectedCustomer(null);}}><aside className="ap-drawer ap-drawer-short" role="dialog" aria-modal="true" aria-label={copy.customerDetails}><div className="ap-drawer-head"><div><span className="ap-section-label">{copy.customerDetails}</span><h2>{selectedCustomer.full_name||"—"}</h2></div><button className="ap-icon" onClick={()=>setSelectedCustomer(null)} aria-label={copy.close}><X/></button></div><div className="ap-drawer-body"><div className="ap-info"><div className="ap-info-grid"><div><span>{copy.role}</span><strong>{roleLabel(selectedCustomer.role)}</strong></div><div><span>{copy.status}</span><strong><StatusBadge status={selectedCustomer.account_status} label={selectedCustomer.account_status==="active"?copy.active:copy.suspended}/></strong></div><div><span>{copy.phone}</span><strong>{selectedCustomer.phone||"—"}</strong></div><div><span>{copy.city}</span><strong>{selectedCustomer.city||"—"}</strong></div><div><span>{copy.created}</span><strong>{fmt(selectedCustomer.created_at)}</strong></div></div></div></div><div className="ap-drawer-foot"><button className={`ap-btn ${selectedCustomer.account_status==="suspended"?"success":""}`} disabled={busyId===selectedCustomer.id||selectedCustomer.id===profile?.id} onClick={()=>void accountAction(selectedCustomer)}>{selectedCustomer.account_status==="suspended"?copy.reactivate:copy.suspend}</button></div></aside></div>}
  {selectedBooking&&<div className="ap-drawer-overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setSelectedBooking(null);}}><aside className="ap-drawer ap-drawer-short" role="dialog" aria-modal="true" aria-label={copy.bookingDetails}><div className="ap-drawer-head"><div><span className="ap-section-label">{copy.bookingDetails}</span><h2>{selectedBooking.service_category||"—"}</h2><p>{bookingLabel(selectedBooking.status)}</p></div><button className="ap-icon" onClick={()=>setSelectedBooking(null)} aria-label={copy.close}><X/></button></div><div className="ap-drawer-body"><div className="ap-info"><div className="ap-info-grid"><div><span>{copy.customer}</span><strong>{selectedBooking.customer_name||"—"}</strong></div><div><span>{copy.provider}</span><strong>{selectedBooking.provider_name||"—"}</strong></div><div><span>{copy.date}</span><strong>{fmt(selectedBooking.service_date||selectedBooking.created_at)}</strong></div><div><span>{copy.status}</span><strong><StatusBadge status={selectedBooking.status} label={bookingLabel(selectedBooking.status)}/></strong></div><div><span>{copy.city}</span><strong>{selectedBooking.location_text||"—"}</strong></div><div><span>{copy.created}</span><strong>{fmt(selectedBooking.created_at)}</strong></div></div></div></div><div className="ap-drawer-foot"><button className="ap-btn" onClick={()=>setSelectedBooking(null)}>{copy.close}</button>{!["completed","cancelled","rejected"].includes(selectedBooking.status)?<button className="ap-btn danger" disabled={busyId===selectedBooking.id} onClick={()=>void cancelBooking()}><Ban size={15}/>{copy.cancel}</button>:null}</div></aside></div>}
 </div>;
}
