import React from "react";
import { createRoot } from "react-dom/client";
import App from "./App";
import "./index.css";
import "./styles/app-shell.css";
import "./styles/design-system.css";
import "./styles/wokka-inspired.css";
import "./styles/wokka-refinements.css";
import "./styles/mobile-shell-fix.css";
import "./styles/final-responsive-polish.css";
import "./styles/final-responsive.css";
import "./styles/header-responsive.css";
import "./styles/final-visual-polish.css";
import "./styles/final-auth.css";
import "./styles/maak-brand-system.css";
import "./styles/maak-shell-polish.css";
import "./styles/maak-final-calibration.css";
import "./styles/admin-premium.css";
import "./styles/admin-final-overrides.css";
import "./styles/admin-command.css";
import "./styles/admin-quality-fixes.css";
import "./styles/admin-brand-and-mobile.css";
import "./styles/admin-identity-lockdown.css";
import "./styles/admin-v2.css";
(function(){try{var stored=sessionStorage.getItem("maak:deep-link");if(stored){sessionStorage.removeItem("maak:deep-link");var current=window.location.pathname+window.location.search+window.location.hash;if(stored!==current)window.history.replaceState({},"",stored)}}catch(_){}})();
if("serviceWorker" in navigator&&window.location.protocol==="https:"){window.addEventListener("load",()=>{navigator.serviceWorker.register("./sw.js",{scope:"./"}).catch(()=>{})})}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);